openapi: 3.0.3
info:
  title: ThinkExeAPI
  description: API for ThinkExe
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/review:
    post:
      summary: Create a new review
      tags:
        - review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewDto"
      responses:
        '201':
          description: Review created successfully
          content:
              application/json:
                schema:
                    $ref: "#/components/schemas/ReviewDto"
        '400':
          description: Bad request
  /api/review/{questId}:
    get:
        tags:
            - review
        summary: Get reviews by quest ID
        operationId: getReviewsByQuestId
        parameters:
            - name: questId
              in: path
              required: true
              schema:
                  type: string
                  description: UUID of the quest to get reviews
        responses:
            '200':
              description: successful operation
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: "#/components/schemas/ReviewDto"
            '400':
              description: Invalid ID supplied
            '404':
              description: Quest not found
components:
  schemas:
    ReviewDto:
      type: object
      required:
        - authorId
        - rating
        - questId
      properties:
        authorId:
          type: string
          description: The ID of the author
        rating:
          type: number
          description: The rating of the review
        questId:
          type: string
          description: The ID of the quest
        comment:
          type: string
          description: The comment of the review
        id:
          type: string
          description: The ID of the review
