openapi: 3.0.3
info:
  title: ThinkExeAPI
  description: API for ThinkExe
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/users/{userId}:
    get:
      tags:
        - user
      summary: Get user by user ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            description: UUID of the user to get
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Update user
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            description: UUID of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Delete user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: UUID of the user to delete
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
  /api/users:
    post:
      tags:
        - user
      summary: Create user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid input
      security:
        - api_key: []

components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
          format: email
        profilePicture:
          type: string
        averageQuizRating:
          type: number
      required:
        - username
        - email