services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network   # <-- Add this line

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port for sending emails
      - "8025:8025"  # Web UI port for viewing emails
    networks:
      - mailhog_network

  frontend:
    build:
      context: ./frontend/frontend-app  # Directory containing the Dockerfile and app
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - mailhog_network

  backend:
    build:
      context: ./backend  # Directory containing the Dockerfile and app
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app
      - SPRING_DATASOURCE_USER=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - mailhog_network
      - postgres_network
    depends_on:
      - postgres
      - mailhog

networks:
  mailhog_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
