version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port for sending emails
      - "8025:8025"  # Web UI port for viewing emails
    networks:
      - mailhog_network

networks:
  mailhog_network:
    driver: bridge

volumes:
  postgres_data:
