app:
  name: dev-mode-backend
  rest:
    port: 8080
  probes:
    port: 8080
  cors:
    origins: "*"
    headers: "*"
spring:
  mail:
    from: thinkexe@localhost.com
    host: localhost
    port: 1025  # MailHog SMTP port
    username: ""  # No authentication needed
    password: ""
    properties:
      mail:
        smtp:
          auth: false  # No authentication required
          starttls:
            enable: false  # No TLS required
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi/ui
    tags-sorter: alpha
    operations-sorter: alpha
  writer-with-order-by-keys: true
jwt:
  secret: mySuperSecretKeyForJWTanditneedstocontainatleast256bits
  expiration: 3600000
